# Generated by Django 2.1 on 2019-09-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('skin_color', models.CharField(max_length=120)),
                ('blood_type', models.CharField(max_length=120)),
                ('amputation_date', models.DateTimeField(auto_now_add=True)),
                ('expiary_date', models.DateTimeField(auto_now_add=True)),
                ('reason_for_amputation', models.TextField()),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
