# Generated by Django 2.2.5 on 2019-09-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
