# Generated by Django 2.2.5 on 2019-09-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_profile_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcheckout',
            name='user',
        ),
        migrations.AlterField(
            model_name='productcheckout',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_checkouts', to='api.Cart'),
        ),
        migrations.AlterField(
            model_name='productcheckout',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
        ),
    ]
