# Generated by Django 2.2.5 on 2019-09-26 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20190926_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_in_use',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcheckout',
            name='price',
            field=models.DecimalField(decimal_places=3, default=django.utils.timezone.now, max_digits=10),
            preserve_default=False,
        ),
    ]
